### ISSUE TITLE
Miis won't save

### ISSUE THREAD

**Issue by FallBackITA27** [HEYimHeroic/MiiStudioMiiLoader#2]
Self explanatory. When saving it will refuse to, giving a generic "An error occurred, retry later."

**Comment by HEYimHeroic** [comment]
are you sure the Mii Studio code you're inputting is correct? go ahead and paste it here so i can confirm.

**Comment by FallBackITA27** [comment]
I might've just fucked up the code. I didn't use github when I made this issue so I never realized I got a response. Thanks tough.
